nvim:
  url: wrnlb666/nvim.conf.git
  target: nvim.conf
tmux: 
  url: wrnlb666/tmux.conf.git
  target: tmux.conf
zsh: 
  url: wrnlb666/zsh.conf.git
  target: zsh.conf
bash: 
  url: wrnlb666/bash.conf.git
  target: bash.conf
git: 
  url: wrnlb666/gitconfig.git
  target: gitconfig
gdb: 
  url: wrnlb666/gdbinit.git
  target: gdbinit
starship: 
  url: wrnlb666/starship.toml.git
  target: starship
btop:
  url: wrnlb666/btop.git
  target: btop
fastfetch:
  url: wrnlb666/fastfetch.conf
  target: fastfetch.conf
omarchy:
  url: wrnlb666/omarchy-setup.git
  target: omarchy
crush:
  url: wrnlb666/crush.conf.git
  target: crush.conf
fcitx5:
  url: wrnlb666/fcitx5.conf.git
  target: fcitx5.conf
